name: numba-examples
channels:
  - defaults
  - numba

dependencies:
  - python=3.8
  - numba=0.49
  - numba-scipy=0.2
  - scipy
  - icc_rt
  - dask
  - progressbar2
  - colorama
  - tbb
  - matplotlib
  - imageio
  - pip
